#!/usr/bin/env python3
"""Add reviewed text-first content for the 1404 English section."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAM_PATH = ROOT / "data/questions/exam_1404.json"

CLOZE = """The first organized international competition involving winter sports ............... (8) just five years after the birth of the modern Olympics in 1896. Known as the Nordic Games, this competition included athletes predominantly from countries such as Norway and Sweden. It was held eight times between 1901 and 1926, ............... (9) all but one time. Figure skating was included in the Olympics for the first time in the 1908 Summer Games in London, ............... (10) the skating competition was not actually held until October, some three months after the other events were over."""

PASSAGE_1 = """Electricity and magnetism were regarded as distinct phenomena for quite a while. However, as scientists started studying electrodynamics, they noticed that current-carrying wires could be affected by magnets, and also that magnetic fields could be generated by currents. Somehow electricity and magnetism were linked. Formally, electromagnetism is the field of physics that looks at how magnetic fields can affect moving electric charges and how changing magnetic fields can induce electric currents. It also looks at how magnetic fields can be generated by electric fields or electric currents. It even explains the origin of electromagnetic radiation. Ultimately, electromagnetism describes electricity and magnetism within one single framework as two manifestations of the same fundamental electromagnetic force.

When learning about electricity and magnetism, you might hear the term “field” come up a lot. But what is an electric field or a magnetic field? A field is a way to describe the effects or influence that a particular type of force has in a way that is independent of what that force might act upon. For example, the effect of the gravitational force that the Earth exerts on objects in its vicinity can be represented by a vector at each point in space around Earth."""

PASSAGE_2 = """Graphene could revolutionize future technologies, making transparent and flexible solar panels, foldable mobile phones or ultrathin computers a reality. Now researchers from Spain, Germany, and the US think they have taken one of the first important steps along the way. Frank H. L. Koppens of the Institut de Ciències Fotòniques (ICFO) in Spain, along with colleagues from MIT and Harvard University, have found that graphene is able to convert a single absorbed photon into multiple electrons. Graphene is currently being employed as an alternative to semiconducting materials for light-to-electricity conversion, but the finding indicates that the material could be more efficient than thought.

“In most materials, one absorbed photon generates one electron, but in the case of graphene, one absorbed photon is able to produce many excited electrons, and therefore generate larger electrical signals,” explains Koppens. “We have found that this process is very efficient: more than 80% of light energy is converted.” Instead of losing excess energy as heat when a photon is absorbed, graphene uses the extra to generate secondary ‘hot’ electrons. These ‘hot’ or excited electrons can drive a current, making graphene an alternative material for light-harvesting photovoltaic devices or photodetection. The reason for graphene’s highly efficient extraction of light energy lies in its unique physical nature. Doped graphene can be thought of as a mixture of a semiconductor, where properties are determined by the behavior of electrons and holes in the conduction and valence bands, and a metal, in which they depend upon the Fermi level."""

PASSAGE_3 = """Let’s start with the basics. A superconductor is a material where electrical resistance disappears and a magnetic field is created. More simply, when you put electricity into a superconductor, you do not lose any energy—a multimeter would register zero volts and zero ohms on a live circuit—and it becomes a magnet. [1] We have known about superconductors since 1911, when a Dutch physicist named Heike Kamerlingh Onnes observed that when he immersed mercury wire in liquid helium, bringing its temperature down to within just a few degrees of Absolute Zero (-273.15°C or 4.2 Kelvin, to be precise), its electrical properties abruptly changed. He wrote, “Mercury has passed into a new state, which on account of its extraordinary electrical properties may be called the superconductive state.” [2] In 1913, he won the Nobel Prize in Physics for his work.

This will not be the only Nobel Prize related to superconductors you will hear about. [3] When experimental physicists prove that something happens, theoretical physicists have to figure out the why of it. A lot of hypotheses were kicked around about superconductivity, as well as suggestions for practical applications. By the 1950s, the US physicists John Bardeen, Leon Cooper, and John Robert Schrieffer had an explanation for low-temperature superconductivity that everyone seems to agree on. [4] Electrons moving through a superconductor can pair up using quantum properties to evade the normal barriers to free movement through a solid. They proved mathematically that this pairing was possible in many substances up to a temperature of around 40 Kelvin, but higher than that the pairs of electrons would be shaken apart by the energy of the warm solid matter. Their work earned them the Nobel Prize in Physics in 1972."""

ITEMS = {
    1: ("My mother was a very strong, ............... woman who was a real adventurer in love with the arts and sports.", ["consecutive", "independent", "enforced", "subsequent"]),
    2: ("The weakened ozone ..............., which is vital to protecting life on Earth, is on track to be restored to full strength within decades.", ["layer", "level", "brim", "ingredient"]),
    3: ("Reading about the extensive food directives some parents leave for their babysitters, I was wondering if these lists are meant to ease ............... feelings for leaving the children in someone else’s care.", ["an affectionate", "a misguided", "an undisturbed", "a guilty"]),
    4: ("He is struck deaf by disease at an early age, but in rigorous and refreshingly unsentimental fashion, he learns to overcome his ............... so that he can keep alive the dream of becoming a physician like his father.", ["ambition", "incompatibility", "handicap", "roughness"]),
    5: ("With cloak and suit manufacturers beginning to ............... their needs for the fall season, trading in the wool goods market showed signs of improvement this week.", ["anticipate", "nullify", "revile", "compliment"]),
    6: ("Sculptors leave highly ............... footprints in the sand of time, and millions of people who never heard the name of Augustus Saint-Gaudens are well-acquainted with his two statues of Lincoln.", ["insipid", "sinister", "conspicuous", "reclusive"]),
    7: ("To avoid liability, officers were told that they need to ............... closely to established department rules and demonstrate that probable cause for an arrest or the issuance of a summons existed.", ["recapitulate", "confide", "hinder", "adhere"]),
    8: ("Choose the best completion for blank (8).", ["was introducing", "was introduced", "introduced", "has been introducing"]),
    9: ("Choose the best completion for blank (9).", ["with Stockholm hosting", "and Stockholm hosting", "that Stockholm hosted", "Stockholm hosted"]),
    10: ("Choose the best completion for blank (10).", ["despite", "although", "otherwise", "notwithstanding"]),
    11: ("The word “generated” in paragraph 1 is closest in meaning to ............... .", ["identified", "controlled", "produced", "analyzed"]),
    12: ("The word “it” in paragraph 1 refers to ............... .", ["electricity", "radiation", "origin", "electromagnetism"]),
    13: ("According to paragraph 1, which of the following in a way demonstrated that electricity and magnetism are not unrelated?", ["Discovery of current-carrying wires", "Studying electrodynamics", "Further progress in electromagnetism", "Discovery of electromagnetic radiation"]),
    14: ("All of the following words are mentioned in the passage EXCEPT ............... .", ["circuits", "wires", "framework", "vector"]),
    15: ("According to the passage, which of the following statements is true?", ["The effect of the gravitational force that the Earth exerts is greater on the objects which are far away from it.", "A field is said to be the influences of a specific kind of force, dependent on the objects upon which that force may act.", "Electromagnetism presents electricity and magnetism as two aspects of the same fundamental electromagnetic force.", "Electromagnetism is unable to explain the origin of electromagnetic radiation and the way currents are produced."]),
    16: ("The word “convert” in paragraph 1 is closest in meaning to ............... .", ["push", "capture", "carry", "transform"]),
    17: ("According to paragraph 1, what is an already-established function of graphene?", ["A replacement for semiconducting materials in certain cases", "A new source of generating light without any necessary input", "A new technology so efficient that it has replaced solar panels of any kind", "An alternative way of producing mobile phones with minimal cost"]),
    18: ("According to paragraph 2, ‘hot’ electrons ............... .", ["is the name applied to all electrons generated by graphene", "are electrons generated by graphene from excess energy otherwise lost as heat", "refers to a specific type of electron used as an input for graphene with an 80% efficiency", "play an insignificant role in the final energy efficiency of the devices that use graphene"]),
    19: ("What does paragraph 2 mainly discuss?", ["The potential risks of graphene", "The origin of graphene", "The advantage of graphene", "The challenge facing graphene technology"]),
    20: ("The passage provides sufficient information to answer which of the following questions?\n\nI. Who discovered graphene?\n\nII. In which country is graphene more commonly used in the industry?\n\nIII. Does graphene’s failure to extract 100% of light energy make it an inefficient material?", ["I and III", "Only II", "I and II", "Only III"]),
    21: ("According to paragraph 1, all of the following are true about Heike Kamerlingh Onnes EXCEPT that ............... .", ["the research leading to his Nobel Prize in physics was conducted sometime in the early 20th century", "after succeeding in discovering the invaluable properties of superconductors, he coined the index ohm to describe one of them", "his studies showed that mercury could transition into a new state, which may be called the superconductive state due to its electrical properties", "when he submerged mercury wire in liquid helium, reducing its temperature to only a few degrees above Absolute Zero, its electrical properties suddenly changed"]),
    22: ("Which of the following techniques is used in paragraph 1?", ["Definition", "Comparison", "Classification", "Exemplification"]),
    23: ("According to paragraph 2, which of the following statements is true?", ["Quantum properties prevent electrons moving through a superconductor from pairing up, resulting in their free movement through a solid.", "When theoretical physicists establish that a phenomenon takes place, experimental physicists enter to clarify the reasons behind it.", "The explanation offered by the three US physicists for low-temperature superconductivity was quickly rejected by physicists in the 1950s.", "It was mathematically demonstrated that above 40 Kelvin, the energy from the warm solid matter would disrupt the pairs of electrons."]),
    24: ("In which position marked by [1], [2], [3] or [4] can the following sentence best be inserted in the passage?\n\n“Over the next two years, he discovered similar properties in tin, lead, then other metals and alloys including niobium-tin, all when cooled down to almost Absolute Zero.”", ["[1]", "[2]", "[3]", "[4]"]),
    25: ("Which of the following best describes the writer’s overall tone in the passage?", ["Objective", "Passionate", "Humorous", "Ironic"]),
}


def main():
    exam = json.loads(EXAM_PATH.read_text(encoding="utf-8"))
    questions = {question["number"]: question for question in exam["questions"]}
    for number, (text, choices) in ITEMS.items():
        question = questions[number]
        question["text"] = text
        question["choice_texts"] = choices
        if 8 <= number <= 10:
            question["context"] = CLOZE
        elif 11 <= number <= 15:
            question["context"] = PASSAGE_1
        elif 16 <= number <= 20:
            question["context"] = PASSAGE_2
        elif 21 <= number <= 25:
            question["context"] = PASSAGE_3
        else:
            question.pop("context", None)
    EXAM_PATH.write_text(json.dumps(exam, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
