#!/usr/bin/env python3
"""Convert the 1402 English section from scans to accessible text."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/questions/exam_1402.json"

CLOZE = """One commentator argues that the success of private schools is not in their money, **(8)** their organization. State schools fail their pupils because, under government control, they lack options. But if head teachers at state schools **(9)** given the same freedom as those at private schools, namely **(10)** poor teachers and pay more to good ones, parents would not need to send their children to private schools any more."""

P1 = """Internal combustion engines have thermodynamic limits on efficiency, expressed as a fraction of energy used to propel the vehicle compared to energy produced by burning fuel. Gasoline engines effectively use only 15% of the fuel energy content to move the vehicle or to power accessories; diesel engines can reach on-board efficiency of 20%; electric vehicles have efficiencies of 69–72%, when counted against stored chemical energy, or around 59–62%, when counted against required energy to recharge.

Electric motors are more efficient than internal combustion engines in converting stored energy into driving a vehicle. However, they are not equally efficient at all speeds. To allow for this, some cars with dual electric motors have one electric motor with a gear optimized for city speeds and the second electric motor with a gear optimized for highway speeds. The electronics select the motor that has the best efficiency for the current speed and acceleration. Regenerative braking, which is most common in electric vehicles, can recover as much as one fifth of the energy normally lost during braking."""

P2 = """Electrical flow in the body (i.e., bioelectricity), plays a significant role in many physiological and pathophysiological conditions (health and disease). Nerves relay information and mediate body functions by transmitting electrical impulses: bioelectrical signals.

Bioelectricity refers to electrical currents occurring within or produced by the human body. Bioelectric currents are generated by a number of different biological processes, and are used by cells to conduct impulses along nerve fibers, to regulate tissue and organ functions, and to govern metabolism.

Bioelectrical currents (and potentials) of human tissue, recorded from the skin surface by electrocardiograph (E.C.G.), electroencephalograph (E.E.G.), electromyography (E.M.G.) and similar sensitive devices, are widely used in medicine to diagnose the condition of various vital organs.

The most important difference between bioelectric current flow in living organisms and the type of electrical current used to produce light, heat, or power is that bioelectrical current is a flow of ions (atoms or molecules carrying an electric charge), while standard electricity is a movement of electrons."""

P3 = """Small-scale wind power is the name given to wind generation systems with the capacity to produce up to 50 kW of electrical power. Isolated communities, which may otherwise rely on diesel generators, may use wind turbines as an alternative. Individuals may purchase these systems to reduce or eliminate their dependence on grid electric power for economic reasons, or to reduce their carbon footprint. Wind turbines have been used for household electric power generation in conjunction with battery storage over many decades in remote areas.

Grid-connected domestic wind turbines may use grid energy storage, thus replacing purchased electric power with locally produced power when available. The surplus power produced by domestic micro-generators can, in some jurisdictions, be fed into the network and sold, producing a retail credit for the micro-generators’ owners to offset their energy costs.

Off-grid system users can either adapt to intermittent power or use batteries, photovoltaic, or diesel systems to supplement the wind turbine. Equipment such as parking meters, traffic warning signs, street lighting, or wireless Internet gateways may be powered by a small wind turbine, possibly combined with a photovoltaic system, which charges a small battery replacing the need for a connection to the power grid.

Distributed generation from renewable resources is increasing as a consequence of the increased awareness of climate change. The electronic interfaces required to connect renewable generation units with the utility system can include additional functions, such as active filtering to enhance the power quality.

Airborne wind turbines, such as kites, can be used in places at risk of hurricanes, as they can be taken down in advance."""

ITEMS = {
1:("Despite the fact that Gross Domestic Product (GDP) has increased substantially in the industrialized West, the levels of human contentment have remained ............... .",["apposite","interwoven","static","implicit"]),
2:("Immigration ............... from the Latin word migration and means the act of a foreigner entering a country in the aim of obtaining the right of permanent residence.",["gathers","obtains","arises","derives"]),
3:("Not speaking the same language as your customers can lead to communication ............... .",["breakdown","brevity","gesture","imitation"]),
4:("The factory’s workforce has ............... from over 4,000 to a few hundred.",["withdrawn","dwindled","undercut","forecasted"]),
5:("The police came up empty-handed despite an ............... exploration of the suspect’s home.",["exhaustive","inescapable","ephemeral","inevitable"]),
6:("When the old man married a woman in her thirties, all everyone talked about was the ............... in the couple’s ages.",["diversity","disparity","longevity","extension"]),
7:("One local factory will ............... the town’s job shortage by providing 250 more jobs.",["overlook","adjust","displace","alleviate"]),
8:("Choose the best completion for blank (8).",["that is","it is in","but in","is"]),
9:("Choose the best completion for blank (9).",["had","were","to be","be"]),
10:("Choose the best completion for blank (10).",["by sacking","sacking","sacked","to sack"]),
11:("This passage is mainly about ............... .",["energy efficiency","electric motors","stored chemical energy","gear optimization"]),
12:("In paragraph 1, the author ............... .",["counts the energy required to charge an engine","advises drivers not to use internal combustion engines","compares a fraction of energy moving a car to energy produced by burning fuel","shows how stored chemical energy converts to energy driving a car in different motors"]),
13:("It is stated in the passage that ............... .",["the gear systems in electric motors should be optimized","electric motors do not have the same efficiency at all speeds","current motors have the best efficiency for speed and acceleration","electric cars have speed limits compared to internal combustion engines"]),
14:("You can infer from the passage, in a conventional braking system, ............... .",["the braking system should be regenerated","20% of the energy is lost during braking","recovering energy is most common","there is a lot of wasted energy"]),
15:("The writer’s tone in this passage is ............... .",["critical","illuminating","subjective","supportive"]),
16:("The best title for this passage is ............... .",["Potentials of human tissues","The science of bioelectricity","Atoms or molecules carrying an electric charge","Bioelectric current flow versus electrical current"]),
17:("The word “relay” in paragraph 1 is similar in meaning to ............... .",["transfer","store","produce","process"]),
18:("Bioelectric currents are utilized by cells to do all of the following EXCEPT ............... .",["regulation of the chemical changes occurring in a cell","transmission of a nerve impulse along a neuron","regeneration of different biological processes","control of body tissues and organs activities"]),
19:("The conditions of main human organs, according to the passage, are assessed through ............... .",["medicines injected into body by recording devices","sensitive devices being widely designed by physicians","various physiological and pathophysiological methods","bioelectrical currents recorded from the skin surface"]),
20:("Electrical power is ............... .",["generated whenever a net ion flux occurs","the interface of an electrode and solution","the flow and current of electrically charged atoms and molecules","energy harnessed from the flow or movement of electrons"]),
21:("According to the passage, small-scale wind power can be a good choice for all of the following EXCEPT ............... .",["eliminating dependence on electric power","reducing the amount of greenhouse gases","using as a low-priced energy source","remote and isolated areas"]),
22:("The micro-generators’ owners, as stated in the passage, can ............... .",["help a utility company to offset its costs","produce a retail credit in some jurisdictions","sell the extra energy to a company supplying electricity","enforce purchased electric power with locally produced power"]),
23:("The word “intermittent” in paragraph 3 can be replaced by ............... .",["indirect","strong","discontinuous","regular"]),
24:("Raising awareness on climate change ............... .",["contributes to enhancing the power quality","makes it necessary to connect the electronic interfaces","causes the use of small batteries common","leads to more power generation from renewable resources"]),
25:("Airborne wind turbines are suitable in places being at risk of hurricanes because ............... .",["we can take them apart and remove them before a hurricane occurs","they are equipped with additional devices in advance","they are already connected to some holder kites","they are resistant to hurricanes"]),
}

def main():
    data=json.loads(DATA.read_text(encoding="utf-8"))
    for q in data["questions"]:
        n=q["number"]
        if n not in ITEMS: continue
        q["text"],q["choice_texts"]=ITEMS[n]
        q.pop("image",None)
        if 8<=n<=10:q["context"]=CLOZE
        elif 11<=n<=15:q["context"]=P1
        elif 16<=n<=20:q["context"]=P2
        elif 21<=n<=25:q["context"]=P3
    data["image_policy"]="English questions are accessible text; technical questions retain contextual official-source crops where needed."
    DATA.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

if __name__=="__main__":main()
